wallpaper {
	monitor = DP-4
	path = /home/swarley/.config/wallpapers/1.jpg
	fit_mode = cover
}

	wallpaper {
	monitor = HDMI-A-5
	path = /home/swarley/.config/wallpapers/1.jpg
	fit_mode = cover
}

splash = false
ipc = off
